# Generated by Django 3.1.1 on 2020-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200914_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
