# Generated by Django 3.1.1 on 2020-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201013_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favoris',
            field=models.BooleanField(null=True),
        ),
    ]
